name: lumi_app
description: "Lumi - Your 8-bit AI Companion powered by on-device Cactus Engine"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.0
  http: ^1.2.0
  google_fonts: ^6.2.1
  ffi: ^2.2.0
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DungGeunMo
      fonts:
        - asset: assets/fonts/DungGeunMo.ttf
